name: t_store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Packages
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  fl_chart: ^0.66.2

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  image_picker: ^1.0.8
  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0
  uuid: ^3.0.7
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  google_generative_ai: ^0.2.0

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  flutter_facebook_auth: ^7.0.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/reviews/
    - assets/images/on_boarding_images/
    - assets/images/content/
    - assets/icons/categories/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/images/user/
    - assets/logos/

  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica_regular.otf
        - asset: assets/fonts/coolvetica_regular_italic.otf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
